# Generated by Django 4.0.1 on 2022-01-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name_of_receiver', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('MUMBAI', 'Mumbai'), ('DELHI', 'Delhi'), ('CHENNAI', 'Chennai'), ('BANGLORE', 'Banglore'), ('KOLKATA', 'Kolkata')], max_length=50)),
            ],
        ),
    ]
